function xn = own_encoder(string, fS, table)
%table entries should look like this (first row should be dismissed)
% 'character'     'frequency'     'Length/Pause'
%    a               523.3            5000
%   ...               ...              ...

if mod(length(string),3) ~= 0
    error('string length must be a multiple of 3; fill with blank characters')
end

A = 1; %Amplitude of sin wave; seen from plot of xn generated by signalgenerator2.p
%f  ... frequency
%s0 ... #samples for t0
%s1 ... #samples for t1
pulse = @(f,s0,s1) [A*sin(2*pi*f*(0:s0)/fS), zeros(1,s1)];


characters = table{:,1};
frequencies = table{:,2};
lengths = table{:,3};


xn = [];
for ii = 1:3:length(string)

    f = frequencies(string(ii) == characters);
    s0 = lengths(string(ii+1) == characters);
    s1 = lengths(string(ii+2) == characters);
    
    xn = [xn, pulse(f,s0,s1)];

end

%Add padding in front and at the end
xn = [zeros(1000,1); xn(:); zeros(1000,1)];


%play the sound!!
soundsc(xn,fS)



end

